on: 
  push:
    branches: 
      - 'development'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: test-terraform-code
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
    steps:
    - uses: actions/checkout@master
      with:
              ref: development
    #- uses: "radudobrinescu/github-actions/terraform-test@master"
    #- uses: "radudobrinescu/github-actions/create-stack@master"
    #  if: success()
    - uses: "radudobrinescu/github-actions/create-dummy-image@master"
      name: Create dummy image
    - uses: actions/upload-artifact@master
      with:
        name: stack-archive
        path: ${GITHUB_WORKSPACE}/upload
  submit-image-listing:
    if: success()
    name: submit-image
    runs-on: ubuntu-latest
    needs: test-terraform-code
    steps:
    - name: submit-image-to-publisher-portal
      run: |
        echo "This will submit the image to Publisher Portal"
