on: 
  push:
    branches: 
      - 'development'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: Update Marketplace Stack Listing
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
    steps:
    - uses: actions/checkout@master
      name: Checkout Quickstart Repo
      with:
              ref: development
    #- uses: "radudobrinescu/github-actions/terraform-test@master"
    #   name: Test Terraform Code
    - uses: "radudobrinescu/github-actions/create-stack@master"
      name: Create Stack Archive
    #  if: success()
    - uses: "radudobrinescu/github-actions/create-dummy-image@master"
      name: Create dummy image
    - uses: "radudobrinescu/github-actions/update-listing@master"
      name: Update Marketplace Listing
