name: TFTesting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install required packages
      run: |
        sudo apt-get install build-essential unzip.
      shell: bash
    - name: Run a multi-line script
      run: |
        echo First exec,
        echo Second exec.
